name: tofi_rbw
description: Uses Tofi to get information from rbw.
version: 0.0.1
# homepage: https://www.example.com

executables:
  tofi-rbw: main

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies: {args: ^2.3.1}

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
